version: '3.7'

services:
    static-web:
        image: projectName:v1
        ports:
            - "publishedPort:80"
        volumes: 
            - nginx:/usr/share/nginx/html
        deploy:
            mode: replicated
            replicas: 1
            endpoint_mode: vip
            resources: 
                limits: 
                    cpus: "cpu"
                    memory: ram
            restart_policy:
                condition: on-failure
                delay: 15s
                max_attempts: 5
                window: 120s
volumes:
    nginx: {}